package events

import "errors"

var (
	ErrInvalidOrganizerID     = errors.New("organizer_id is required and must be a valid uuid")
	ErrInvalidCategoryID      = errors.New("category_id is required and must be a valid uuid")
	ErrInvalidEventID         = errors.New("event_id must be a valid uuid")
	ErrInvalidSessionID       = errors.New("session_id must be a valid uuid")
	ErrInvalidTicketTypeID    = errors.New("ticket_type_id must be a valid uuid")
	ErrInvalidTitle           = errors.New("title is required")
	ErrInvalidSlug            = errors.New("slug is required")
	ErrInvalidDescription     = errors.New("description is required")
	ErrInvalidVenueName       = errors.New("venue_name is required")
	ErrInvalidVenueAddress    = errors.New("venue_address is required")
	ErrInvalidCity            = errors.New("city is required")
	ErrInvalidCountry         = errors.New("country is required")
	ErrInvalidLatitude        = errors.New("latitude must be between -90 and 90")
	ErrInvalidLongitude       = errors.New("longitude must be between -180 and 180")
	ErrInvalidCoordinates     = errors.New("latitude and longitude must be provided together")
	ErrInvalidCurrency        = errors.New("currency is required")
	ErrInvalidStatus          = errors.New("status must be one of: draft, published, cancelled")
	ErrInvalidSessionStatus   = errors.New("status must be one of: scheduled, completed, cancelled")
	ErrInvalidStartsAt        = errors.New("starts_at is required")
	ErrInvalidEndsAt          = errors.New("ends_at must be after starts_at")
	ErrInvalidSalesWindow     = errors.New("sales window is invalid")
	ErrInvalidTicketName      = errors.New("name is required")
	ErrInvalidTicketPrice     = errors.New("price must be greater than or equal to 0")
	ErrInvalidTicketQuantity  = errors.New("quantity must be greater than 0")
	ErrInvalidMaxPerOrder     = errors.New("max_per_order must be greater than 0 and cannot exceed quantity")
	ErrEventNotFound          = errors.New("event not found")
	ErrEventSlugAlreadyExists = errors.New("event slug already exists")
	ErrEventSessionNotFound   = errors.New("event session not found")
	ErrTicketTypeNotFound     = errors.New("ticket type not found")
	ErrCategoryNotFound       = errors.New("category not found")
	ErrOrganizerNotFound      = errors.New("organizer not found")
	ErrForbidden              = errors.New("forbidden")
	ErrOrganizerScopeRequired = errors.New("organizer scope is required for this account")
	ErrUnsupportedRole        = errors.New("role is not allowed to manage events")
)
